export const ROOT_NUMBERS = [
  {
    id: "root1",
    number: 1,
    symbol: "1",
    name: "Root Number 1",
    rulingPlanet: "Sun",
    shortDesc: "Born to lead, shine, and command attention.",
    fullDesc:
      "You usually move ahead with confidence, prefer independent decisions, and naturally carry leadership energy.",
    positiveTraits: ["Leadership", "Confidence", "Strong will", "Independence"],
    cautionTraits: ["Ego", "Stubbornness", "Impatience"],
    career: ["Administration", "Government", "Politics", "Medical"],
    health: ["Heart sensitivity", "Eyesight", "Head stress"],
    luckyNumbers: [1, 2, 3, 9],
    luckyDays: ["Sunday", "Monday", "Tuesday", "Thursday"],
    luckyColors: ["Orange", "Yellow", "Off White", "Red"],
    luckyStone: "Ruby",
    otherFavorableStones: [
      "Yellow Sapphire",
      "Topaz",
      "Yellow Diamond",
      "Amber",
    ],
  },

  {
    id: "root2",
    number: 2,
    symbol: "2",
    name: "Root Number 2",
    rulingPlanet: "Moon",
    shortDesc: "Soft-hearted, intuitive, and emotionally aware.",
    fullDesc:
      "You usually understand feelings deeply and prefer peace, harmony, and emotional connection.",
    positiveTraits: [
      "Sensitivity",
      "Kindness",
      "Intuition",
      "Supportive nature",
    ],
    cautionTraits: ["Mood changes", "Overtrust", "Emotional hurt"],
    career: ["Creative work", "Travel", "Agriculture"],
    health: ["Cold tendency", "Lung sensitivity"],
    luckyNumbers: [2, 1, 5, 6, 9],
    luckyDays: ["Monday", "Sunday", "Wednesday", "Friday"],
    luckyColors: ["White", "Cream", "Green"],
    luckyStone: "Pearl",
    otherFavorableStones: ["Moonstone", "Light Green Jade"],
  },

  {
    id: "root3",
    number: 3,
    symbol: "3",
    name: "Root Number 3",
    rulingPlanet: "Jupiter",
    shortDesc: "Wisdom, ambition, and natural authority.",
    fullDesc:
      "You often seek growth, learning, and respect through structured effort and responsibility.",
    positiveTraits: ["Wisdom", "Discipline", "Guidance", "Responsibility"],
    cautionTraits: ["Rigidity", "Strict attitude"],
    career: ["Administration", "Adviser", "Judiciary"],
    health: ["Throat sensitivity", "Stress"],
    luckyNumbers: [3, 1, 2, 9],
    luckyDays: ["Thursday", "Sunday"],
    luckyColors: ["Yellow", "Blue", "Red"],
    luckyStone: "Yellow Sapphire",
    otherFavorableStones: ["Amethyst", "Citrine", "Tiger Eye", "Yellow Agate"],
  },

  {
    id: "root4",
    number: 4,
    symbol: "4",
    name: "Root Number 4",
    rulingPlanet: "Rahu",
    shortDesc: "Different thinking and unusual life path.",
    fullDesc:
      "You often think differently, prefer your own methods, and experience unexpected life turns.",
    positiveTraits: ["Original thinking", "Practical mind"],
    cautionTraits: ["Restlessness", "Confusion"],
    career: ["Design", "Computers", "Politics"],
    health: ["Gastric", "Mental stress"],
    luckyNumbers: [4, 6, 8],
    luckyDays: ["Saturday", "Friday"],
    luckyColors: ["Grey", "Electric Blue"],
    luckyStone: "Hessonite",
    otherFavorableStones: ["Black Agate", "Black Sapphire"],
  },

  {
    id: "root5",
    number: 5,
    symbol: "5",
    name: "Root Number 5",
    rulingPlanet: "Mercury",
    shortDesc: "Sharp mind and quick communication.",
    fullDesc:
      "You learn fast, adapt quickly, and often succeed through intelligence and communication.",
    positiveTraits: ["Fast thinking", "Communication", "Adaptability"],
    cautionTraits: ["Restlessness", "Overthinking"],
    career: ["Writing", "Banking", "Trading"],
    health: ["Mental stress", "Insomnia"],
    luckyNumbers: [5, 1, 6],
    luckyDays: ["Wednesday", "Friday"],
    luckyColors: ["Green", "White"],
    luckyStone: "Emerald",
    otherFavorableStones: ["Diamond", "Onyx", "Crystal"],
  },

  {
    id: "root6",
    number: 6,
    symbol: "6",
    name: "Root Number 6",
    rulingPlanet: "Venus",
    shortDesc: "Charm, comfort, and harmony.",
    fullDesc: "You value beauty, relationships, and balanced surroundings.",
    positiveTraits: ["Charm", "Harmony", "Relationship skill"],
    cautionTraits: ["Luxury excess", "Attachment"],
    career: ["Fashion", "Hotel", "Music"],
    health: ["Kidney sensitivity", "Throat sensitivity"],
    luckyNumbers: [6, 5, 3, 9],
    luckyDays: ["Friday", "Thursday"],
    luckyColors: ["White", "Pink", "Blue"],
    luckyStone: "Diamond",
    otherFavorableStones: ["Opal", "Zircon", "Emerald"],
  },

  {
    id: "root7",
    number: 7,
    symbol: "7",
    name: "Root Number 7",
    rulingPlanet: "Ketu",
    shortDesc: "Deep mind and intuitive insight.",
    fullDesc: "You think deeply, question life, and often seek hidden meaning.",
    positiveTraits: ["Intuition", "Research", "Inner depth"],
    cautionTraits: ["Isolation", "Overthinking"],
    career: ["Writing", "Healing", "Occult"],
    health: ["Stress", "Insomnia"],
    luckyNumbers: [7, 6, 9, 2],
    luckyDays: ["Tuesday", "Friday"],
    luckyColors: ["Khaki", "Green"],
    luckyStone: "Cat's Eye",
    otherFavorableStones: ["Moonstone", "Pearl", "Moss Agate"],
  },

  {
    id: "root8",
    number: 8,
    symbol: "8",
    name: "Root Number 8",
    rulingPlanet: "Saturn",
    shortDesc: "Patience, endurance, and long success.",
    fullDesc: "You usually progress through discipline, effort, and maturity.",
    positiveTraits: ["Patience", "Responsibility"],
    cautionTraits: ["Delay frustration", "Heavy thinking"],
    career: ["Industry", "Law", "Construction"],
    health: ["Liver sensitivity", "Joint pain"],
    luckyNumbers: [8, 4, 6, 5],
    luckyDays: ["Saturday", "Wednesday"],
    luckyColors: ["Blue", "Black"],
    luckyStone: "Blue Sapphire",
    otherFavorableStones: ["Amethyst", "Lapis Lazuli", "Black Pearl"],
  },

  {
    id: "root9",
    number: 9,
    symbol: "9",
    name: "Root Number 9",
    rulingPlanet: "Mars",
    shortDesc: "Courage, fire, and strong action.",
    fullDesc:
      "You act boldly, take initiative quickly, and face challenges directly.",
    positiveTraits: ["Courage", "Action", "Determination"],
    cautionTraits: ["Anger", "Impulsiveness"],
    career: ["Police", "Medical", "Administration"],
    health: ["Fever tendency", "Blood sensitivity"],
    luckyNumbers: [9, 3, 1, 2, 6],
    luckyDays: ["Tuesday", "Thursday"],
    luckyColors: ["Red", "Pink"],
    luckyStone: "Red Coral",
    otherFavorableStones: ["Ruby", "Garnet", "Bloodstone"],
  },
];
