

export const PLANET_BY_NUMBER = {
  1: "Sun",
  2: "Moon",
  3: "Jupiter",
  4: "Rahu",
  5: "Mercury",
  6: "Venus",
  7: "Ketu",
  8: "Saturn",
  9: "Mars",
};
export const RELATION_META = {
  bestfriend: {
    label: "Best Friend",
    verdict: "Highly Favorable",
  },
  friend: {
    label: "Friend",
    verdict: "Supportive",
  },
  neutral: {
    label: "Neutral",
    verdict: "Balanced",
  },
  enemy: {
    label: "Enemy",
    verdict: "Challenging",
  },
};
export const COMPAT = {
  1: {
    1: "bestfriend",
    2: "friend",
    3: "friend",
    4: "enemy",
    5: "enemy",
    6: "friend",
    7: "friend",
    8: "neutral",
    9: "friend",
  },
  2: {
    1: "friend",
    2: "bestfriend",
    3: "neutral",
    4: "friend",
    5: "enemy",
    6: "bestfriend",
    7: "friend",
    8: "neutral",
    9: "bestfriend",
  },
  3: {
    1: "friend",
    2: "neutral",
    3: "bestfriend",
    4: "neutral",
    5: "friend",
    6: "bestfriend",
    7: "neutral",
    8: "enemy",
    9: "bestfriend",
  },
  4: {
    1: "enemy",
    2: "friend",
    3: "neutral",
    4: "bestfriend",
    5: "neutral",
    6: "bestfriend",
    7: "friend",
    8: "friend",
    9: "friend",
  },
  5: {
    1: "enemy",
    2: "enemy",
    3: "friend",
    4: "neutral",
    5: "bestfriend",
    6: "neutral",
    7: "neutral",
    8: "neutral",
    9: "neutral",
  },
  6: {
    1: "friend",
    2: "bestfriend",
    3: "bestfriend",
    4: "bestfriend",
    5: "neutral",
    6: "bestfriend",
    7: "neutral",
    8: "neutral",
    9: "bestfriend",
  },
  7: {
    1: "friend",
    2: "friend",
    3: "neutral",
    4: "friend",
    5: "neutral",
    6: "friend",
    7: "bestfriend",
    8: "neutral",
    9: "bestfriend",
  },
  8: {
    1: "neutral",
    2: "neutral",
    3: "enemy",
    4: "friend",
    5: "neutral",
    6: "friend",
    7: "neutral",
    8: "bestfriend",
    9: "neutral",
  },
  9: {
    1: "friend",
    2: "bestfriend",
    3: "bestfriend",
    4: "friend",
    5: "neutral",
    6: "bestfriend",
    7: "bestfriend",
    8: "neutral",
    9: "bestfriend",
  },
};
