export const DOB_NUMBERS = [
  {
    id: "dob1",
    day: 1,
    symbol: "1",
    name: "Date of Birth 1",
    rulingPlanet: "Sun",
    shortDesc: "Strong individuality, leadership, and visible personal authority.",
    fullDesc: "You usually carry strong self-belief and prefer moving independently in life. Leadership often appears naturally in your decisions and actions. Respect and recognition remain important for inner satisfaction. You may dislike outside control when your vision feels clear. Balanced confidence usually helps you create strong personal impact.",
    positiveTraits: ["Leadership", "Confidence", "Independence"],
    cautionTraits: ["Ego", "Rigidity", "Impatience"],
    career: ["Administration", "Government", "Leadership"],
    health: ["Head stress", "Eyes", "Blood pressure"],
    luckyNumbers: [1, 2, 3, 9],
    luckyDays: ["Sunday", "Monday", "Tuesday"],
    luckyColors: ["Orange", "Yellow"],
    luckyStone: "Ruby",
    favroableStone: ["Red Garnet", "Sunela"]
  },

  {
    id: "dob2",
    day: 2,
    symbol: "2",
    name: "Date of Birth 2",
    rulingPlanet: "Moon",
    shortDesc: "Sensitive mind, emotional depth, and gentle behaviour.",
    fullDesc: "You usually respond to life through feelings and emotional understanding. Relationships influence your decisions more deeply than others may notice. A soft nature often helps you connect with people naturally. Mood changes may affect clarity during important moments. Calm surroundings usually strengthen your inner balance.",
    positiveTraits: ["Sensitivity", "Kindness", "Supportive nature"],
    cautionTraits: ["Mood change", "Overtrust"],
    career: ["Creative work", "Travel", "Support roles"],
    health: ["Cold", "Lungs", "Hormonal sensitivity"],
    luckyNumbers: [2, 1, 5],
    luckyDays: ["Monday", "Sunday"],
    luckyColors: ["White", "Cream"],
    luckyStone: "Pearl",
    favroableStone: ["Moonstone", "Opal", "White Coral"]
  },

  {
    id: "dob3",
    day: 3,
    symbol: "3",
    name: "Date of Birth 3",
    rulingPlanet: "Jupiter",
    shortDesc: "Wisdom, expression, and natural growth orientation.",
    fullDesc: "You often move forward through knowledge, guidance, and structured effort. Respect and meaningful progress usually matter strongly in life. Your thinking often becomes mature with age and responsibility. High expectations may create pressure when results delay. Balanced discipline usually improves long-term success.",
    positiveTraits: ["Wisdom", "Guidance", "Responsibility"],
    cautionTraits: ["Rigidity", "Overexpectation"],
    career: ["Teaching", "Administration", "Advisory"],
    health: ["Throat", "Stress"],
    luckyNumbers: [3, 1, 2, 9],
    luckyDays: ["Thursday", "Sunday"],
    luckyColors: ["Yellow"],
    luckyStone: "Yellow Sapphire",
    favroableStone: ["Citrine", "Yellow Topaz"]
  },

  {
    id: "dob4",
    day: 4,
    symbol: "4",
    name: "Date of Birth 4",
    rulingPlanet: "Rahu",
    shortDesc: "Different thinking, unusual ideas, and practical intensity.",
    fullDesc: "You often think differently and notice possibilities others miss. Practical intelligence becomes stronger through unusual life experiences. Sudden changes may shape important decisions. Inner restlessness can appear when plans remain uncertain. Patience usually helps your originality become productive.",
    positiveTraits: ["Original thinking", "Practical mind", "Bold ideas"],
    cautionTraits: ["Mental stress", "Restlessness"],
    career: ["Politics", "Design", "Computers"],
    health: ["Gastric", "Stress"],
    luckyNumbers: [4, 6, 8],
    luckyDays: ["Saturday", "Friday"],
    luckyColors: ["Grey", "Blue"],
    luckyStone: "Hessonite",
    favroableStone: ["Honey Garnet", "Cinnamon Stone"]
  },

  {
    id: "dob5",
    day: 5,
    symbol: "5",
    name: "Date of Birth 5",
    rulingPlanet: "Mercury",
    shortDesc: "Fast mind, communication skill, and adaptability.",
    fullDesc: "You usually think quickly and adapt easily to changing situations. Communication often becomes one of your strongest advantages. New ideas and movement keep your mind active. Too many directions may reduce consistency. Clear focus usually improves practical success.",
    positiveTraits: ["Communication", "Fast thinking", "Adaptability"],
    cautionTraits: ["Restlessness", "Overthinking"],
    career: ["Writing", "Trading", "Banking"],
    health: ["Stress", "Insomnia"],
    luckyNumbers: [5, 1, 6],
    luckyDays: ["Wednesday", "Friday"],
    luckyColors: ["Green"],
    luckyStone: "Emerald",
    favroableStone: ["Green Jade", "Peridot"]
  },

  {
    id: "dob6",
    day: 6,
    symbol: "6",
    name: "Date of Birth 6",
    rulingPlanet: "Venus",
    shortDesc: "Charm, harmony, and attraction naturally appear in life.",
    fullDesc: "You usually create comfort and harmony around yourself naturally. Relationships often influence major decisions strongly. Beauty, balance, and emotional warmth matter deeply. Attachment may increase when expectations become personal. Balanced choices usually support stable happiness.",
    positiveTraits: ["Charm", "Harmony", "Relationship skill"],
    cautionTraits: ["Attachment", "Luxury excess"],
    career: ["Fashion", "Finance", "Music"],
    health: ["Kidney sensitivity", "Throat"],
    luckyNumbers: [6, 5, 3, 9],
    luckyDays: ["Friday", "Thursday"],
    luckyColors: ["White", "Pink"],
    luckyStone: "Diamond",
    favroableStone: ["White Zircon", "Opal"]
  },

  {
    id: "dob7",
    day: 7,
    symbol: "7",
    name: "Date of Birth 7",
    rulingPlanet: "Ketu",
    shortDesc: "Inner depth, intuition, and silent observation.",
    fullDesc: "You usually observe deeply before trusting situations fully. Inner analysis often becomes stronger than outer expression. Spiritual curiosity or hidden thinking may remain active throughout life. Emotional distance can appear during pressure. Inner balance usually sharpens intuition further.",
    positiveTraits: ["Intuition", "Research", "Depth"],
    cautionTraits: ["Isolation", "Overthinking"],
    career: ["Writing", "Healing", "Occult"],
    health: ["Stress", "Sleep issues"],
    luckyNumbers: [7, 2, 6, 9],
    luckyDays: ["Monday", "Tuesday"],
    luckyColors: ["Green", "White"],
    luckyStone: "Cat's Eye",
    favroableStone: ["Alexandrite", "Moonstone"]
  },

  {
    id: "dob8",
    day: 8,
    symbol: "8",
    name: "Date of Birth 8",
    rulingPlanet: "Saturn",
    shortDesc: "Discipline, endurance, and serious life lessons.",
    fullDesc: "You usually progress through patience more than speed. Responsibility often arrives early and shapes maturity deeply. Delayed success may still become stable and lasting. Heavy thinking can appear during demanding phases. Steady discipline usually builds long-term credibility.",
    positiveTraits: ["Patience", "Responsibility", "Endurance"],
    cautionTraits: ["Delay frustration", "Heavy thinking"],
    career: ["Industry", "Law", "Construction"],
    health: ["Joint pain", "Liver sensitivity"],
    luckyNumbers: [8, 4, 6],
    luckyDays: ["Saturday", "Friday"],
    luckyColors: ["Blue", "Black"],
    luckyStone: "Blue Sapphire",
    favroableStone: ["Amethyst", "Iolite"]
  },

  {
    id: "dob9",
    day: 9,
    symbol: "9",
    name: "Date of Birth 9",
    rulingPlanet: "Mars",
    shortDesc: "Action, courage, and energetic force dominate life.",
    fullDesc: "You usually react directly and move quickly in important situations. Courage becomes visible when challenges appear. Strong will often helps you protect what matters. Anger may rise when resistance feels unfair. Balanced energy usually brings strong achievement.",
    positiveTraits: ["Courage", "Action", "Determination"],
    cautionTraits: ["Anger", "Impulsiveness"],
    career: ["Police", "Medical", "Administration"],
    health: ["Blood heat", "Injury tendency"],
    luckyNumbers: [9, 3, 1, 6],
    luckyDays: ["Tuesday", "Sunday"],
    luckyColors: ["Red", "Pink"],
    luckyStone: "Red Coral",
    favroableStone: ["Carnelian", "Bloodstone"]
  },

    {
    id: "dob10",
    day: 10,
    symbol: "10",
    name: "Date of Birth 10",
    rulingPlanet: "Sun",
    shortDesc: "Powerful Sun vibration with multiplied individuality and visibility.",
    fullDesc: "You often carry amplified self-confidence and a strong need to create your own place in life. Leadership may appear naturally in practical matters. Recognition and authority often remain important motivations. Pressure can increase when expectations become too high. Balanced effort usually brings visible success.",
    positiveTraits: ["Leadership", "Confidence", "Authority"],
    cautionTraits: ["Ego", "Pressure", "Rigidity"],
    career: ["Administration", "Government", "Politics", "Medical"],
    health: ["Blood pressure", "Head stress", "Eyesight"],
    luckyNumbers: [1, 10, 19, 28],
    luckyDays: ["Sunday", "Monday", "Tuesday", "Thursday"],
    luckyColors: ["Saffron", "Orange", "Light Yellow"],
    luckyStone: "Ruby",
    favroableStone: ["Red Garnet", "Sunela"]
  },

  {
    id: "dob11",
    day: 11,
    symbol: "11",
    name: "Date of Birth 11",
    rulingPlanet: "Moon",
    shortDesc: "Master number with intuition, emotional power, and natural attraction.",
    fullDesc: "You often carry unusual sensitivity along with visible personal influence. Emotional depth and intuition remain stronger than average. People may naturally feel drawn toward your presence. Small emotional disturbances can stay in the mind longer than expected. Inner balance usually improves fortune greatly.",
    positiveTraits: ["Intuition", "Attraction", "Moral strength"],
    cautionTraits: ["Emotional hurt", "Pride", "Stress"],
    career: ["Administration", "Medical", "Creative work", "Leadership"],
    health: ["Cold", "Mental stress", "Digestive sensitivity"],
    luckyNumbers: [1, 2, 11, 29],
    luckyDays: ["Monday", "Sunday", "Thursday"],
    luckyColors: ["White", "Cream", "Light Green"],
    luckyStone: "Pearl",
    favroableStone: ["Moonstone", "Opal", "Ruby"]
  },

  {
    id: "dob12",
    day: 12,
    symbol: "12",
    name: "Date of Birth 12",
    rulingPlanet: "Jupiter",
    shortDesc: "Moon and Sun combine to create thoughtful Jupiter expression.",
    fullDesc: "You usually carry emotional softness along with intellectual growth. Communication often becomes an important strength in life. Ideas may come naturally and people often value your advice. Slow decisions may happen when both heart and mind stay active. Structured learning usually improves progress.",
    positiveTraits: ["Wisdom", "Friendliness", "Creativity"],
    cautionTraits: ["Indecision", "Mental overload"],
    career: ["Teaching", "Writing", "Counselling", "Administration"],
    health: ["Throat", "Stress", "Cholesterol tendency"],
    luckyNumbers: [3, 1, 2, 9],
    luckyDays: ["Thursday", "Sunday", "Monday"],
    luckyColors: ["Yellow", "Cream", "Crimson"],
    luckyStone: "Yellow Sapphire",
    favroableStone: ["Citrine", "Yellow Topaz", "Pearl"]
  },

  {
    id: "dob13",
    day: 13,
    symbol: "13",
    name: "Date of Birth 13",
    rulingPlanet: "Rahu",
    shortDesc: "Sun and Jupiter combine into a forceful Rahu pattern.",
    fullDesc: "You often think independently and prefer creating results through your own methods. Unusual ideas may become practical strengths over time. Leadership appears when situations demand courage. Hidden tension may arise when authority creates conflict. Flexibility usually improves long-term outcomes.",
    positiveTraits: ["Originality", "Strategy", "Leadership"],
    cautionTraits: ["Stubbornness", "Mental stress"],
    career: ["Politics", "Design", "Law", "Technology"],
    health: ["Vata imbalance", "Stress", "Breathing issues"],
    luckyNumbers: [4],
    luckyDays: ["Sunday", "Thursday"],
    luckyColors: ["Grey", "Electric Blue"],
    luckyStone: "Hessonite",
    favroableStone: ["Honey Garnet", "Cinnamon Stone", "Yellow Sapphire"]
  },

  {
    id: "dob14",
    day: 14,
    symbol: "14",
    name: "Date of Birth 14",
    rulingPlanet: "Mercury",
    shortDesc: "Fast-moving intelligence with changing life patterns.",
    fullDesc: "You usually think quickly and understand changing situations rapidly. Communication and flexibility often help you move ahead. Life may bring repeated movement or unexpected adjustments. Mental restlessness can affect consistency. Clear planning usually improves stability.",
    positiveTraits: ["Intelligence", "Adaptability", "Communication"],
    cautionTraits: ["Restlessness", "Impatience"],
    career: ["Business", "Media", "Sales", "Writing"],
    health: ["Nerves", "Sleep disturbance"],
    luckyNumbers: [5],
    luckyDays: ["Wednesday"],
    luckyColors: ["Green"],
    luckyStone: "Emerald",
    favroableStone: ["Green Jade", "Peridot", "Diamond"]
  },

  {
    id: "dob15",
    day: 15,
    symbol: "15",
    name: "Date of Birth 15",
    rulingPlanet: "Venus",
    shortDesc: "Attraction, creativity, and emotional magnetism become strong.",
    fullDesc: "You often influence others through warmth, charm, and expression. Relationships usually play an important role in emotional growth. Creativity may appear naturally in speech or behaviour. Attachment can increase when expectations deepen. Balanced choices usually support harmony.",
    positiveTraits: ["Charm", "Creativity", "Warmth"],
    cautionTraits: ["Attachment", "Luxury tendency"],
    career: ["Arts", "Hospitality", "Design"],
    health: ["Hormonal sensitivity", "Throat"],
    luckyNumbers: [6],
    luckyDays: ["Friday"],
    luckyColors: ["White", "Pink"],
    luckyStone: "Diamond",
    favroableStone: ["White Zircon", "Opal", "Emerald"]
  },

  {
    id: "dob16",
    day: 16,
    symbol: "16",
    name: "Date of Birth 16",
    rulingPlanet: "Ketu",
    shortDesc: "Deep inner analysis and karmic learning shape this date.",
    fullDesc: "You usually think deeply before trusting people or situations. Inner observation often becomes stronger than outer expression. Spiritual or hidden subjects may attract your attention naturally. Sudden emotional withdrawal may appear during pressure. Inner maturity usually strengthens intuition.",
    positiveTraits: ["Intuition", "Depth", "Inner maturity"],
    cautionTraits: ["Isolation", "Mental pressure"],
    career: ["Research", "Occult", "Writing"],
    health: ["Sleep issues", "Stress"],
    luckyNumbers: [7],
    luckyDays: ["Monday", "Tuesday"],
    luckyColors: ["Green", "White"],
    luckyStone: "Cat's Eye",
    favroableStone: ["Alexandrite", "Moonstone", "Pearl"]
  },

  {
    id: "dob17",
    day: 17,
    symbol: "17",
    name: "Date of Birth 17",
    rulingPlanet: "Saturn",
    shortDesc: "Disciplined ambition with visible strength and delayed stability.",
    fullDesc: "You usually move through life with serious goals and practical focus. Long-term effort often brings stronger results than quick success. Respect grows through patience and reliability. Delays may test confidence during important phases. Structured effort usually builds lasting credibility.",
    positiveTraits: ["Endurance", "Discipline", "Stability"],
    cautionTraits: ["Delay frustration", "Heaviness"],
    career: ["Industry", "Management", "Law"],
    health: ["Joints", "Liver"],
    luckyNumbers: [8],
    luckyDays: ["Saturday", "Friday"],
    luckyColors: ["Blue", "Dark Grey"],
    luckyStone: "Blue Sapphire",
    favroableStone: ["Amethyst", "Iolite", "Ruby"]
  },

  {
    id: "dob18",
    day: 18,
    symbol: "18",
    name: "Date of Birth 18",
    rulingPlanet: "Mars",
    shortDesc: "Strong action force with emotional intensity.",
    fullDesc: "You often face difficult situations directly and respond with courage. Emotional force becomes strong when challenged. Protective instincts may appear naturally in relationships. Anger can rise quickly if pressure increases. Balanced energy usually creates strong achievement.",
    positiveTraits: ["Courage", "Action", "Determination"],
    cautionTraits: ["Anger", "Conflict"],
    career: ["Force", "Medical", "Administration"],
    health: ["Blood heat", "Injury tendency"],
    luckyNumbers: [9],
    luckyDays: ["Tuesday", "Sunday"],
    luckyColors: ["Red", "Crimson"],
    luckyStone: "Red Coral",
    favroableStone: ["Carnelian", "Bloodstone", "Pearl"]
  },

  {
    id: "dob19",
    day: 19,
    symbol: "19",
    name: "Date of Birth 19",
    rulingPlanet: "Sun",
    shortDesc: "Sun and Mars combine into powerful self-driven leadership.",
    fullDesc: "You usually carry strong independence with visible courage. Initiative appears naturally in practical situations. Ambition often becomes a strong driving force. Pride may increase when recognition feels delayed. Balanced confidence usually strengthens leadership.",
    positiveTraits: ["Leadership", "Courage", "Initiative"],
    cautionTraits: ["Ego", "Harshness"],
    career: ["Administration", "Politics", "Planning"],
    health: ["Blood pressure", "Head stress"],
    luckyNumbers: [1, 10, 19, 28],
    luckyDays: ["Sunday", "Tuesday", "Thursday"],
    luckyColors: ["Orange", "Golden"],
    luckyStone: "Ruby",
    favroableStone: ["Red Garnet", "Sunela"]
  },

  {
    id: "dob20",
    day: 20,
    symbol: "20",
    name: "Date of Birth 20",
    rulingPlanet: "Moon",
    shortDesc: "Powerful Moon influence with softness and emotional intelligence.",
    fullDesc: "You usually remain caring, polite, and emotionally aware. Relationships strongly influence your peace of mind. Hidden worries may remain inside even when behaviour appears calm. Supportive environments improve clarity. Emotional balance usually strengthens progress.",
    positiveTraits: ["Sensitivity", "Care", "Diplomacy"],
    cautionTraits: ["Mood variation", "Worry"],
    career: ["Creative work", "Travel", "Support roles"],
    health: ["Cold", "Digestive sensitivity"],
    luckyNumbers: [2, 11, 20, 29],
    luckyDays: ["Monday", "Sunday", "Friday"],
    luckyColors: ["White", "Cream", "Light Green"],
    luckyStone: "Pearl",
    favroableStone: ["Moonstone", "Opal", "White Coral"]
  },

  {
    id: "dob21",
    day: 21,
    symbol: "21",
    name: "Date of Birth 21",
    rulingPlanet: "Jupiter",
    shortDesc: "Expressive wisdom and natural optimism become visible.",
    fullDesc: "You usually combine emotional softness with confidence in expression. Friendly behaviour often attracts people naturally. Learning and communication improve life direction. Emotional fluctuation may affect consistency. Balanced thinking usually supports social growth.",
    positiveTraits: ["Wisdom", "Humour", "Friendliness"],
    cautionTraits: ["Emotional fluctuation", "Dependency"],
    career: ["Teaching", "Writing", "Public speaking"],
    health: ["Stress", "Digestive sensitivity"],
    luckyNumbers: [3, 1, 2],
    luckyDays: ["Thursday", "Sunday", "Monday"],
    luckyColors: ["Yellow", "Cream"],
    luckyStone: "Yellow Sapphire",
    favroableStone: ["Citrine", "Yellow Topaz", "Pearl"]
  },

  {
    id: "dob22",
    day: 22,
    symbol: "22",
    name: "Date of Birth 22",
    rulingPlanet: "Rahu",
    shortDesc: "Master builder vibration with strong planning ability.",
    fullDesc: "You usually think in larger structures and long-term results. Practical vision may remain stronger than ordinary expectations. Hidden pressure often increases because goals feel important. Different thinking helps create uncommon paths. Patience usually converts ideas into achievement.",
    positiveTraits: ["Planning", "Originality", "Structure"],
    cautionTraits: ["Mental pressure", "Restlessness"],
    career: ["Construction", "Technology", "Administration"],
    health: ["Stress", "Gastric"],
    luckyNumbers: [4, 6],
    luckyDays: ["Saturday", "Friday"],
    luckyColors: ["Grey", "Blue"],
    luckyStone: "Hessonite",
    favroableStone: ["Honey Garnet", "Cinnamon Stone", "Blue Sapphire"]
  },

  {
    id: "dob23",
    day: 23,
    symbol: "23",
    name: "Date of Birth 23",
    rulingPlanet: "Mercury",
    shortDesc: "Sharp Mercury intelligence with social adaptability.",
    fullDesc: "You usually understand situations quickly and respond effectively. Communication often creates important opportunities. Flexibility helps you move through changing environments. Mental speed may create impatience at times. Focus usually strengthens results.",
    positiveTraits: ["Communication", "Sharp mind", "Adaptability"],
    cautionTraits: ["Mental overactivity", "Impatience"],
    career: ["Business", "Media", "Counselling"],
    health: ["Nerves", "Sleep issues"],
    luckyNumbers: [5, 2, 3],
    luckyDays: ["Wednesday", "Monday", "Thursday"],
    luckyColors: ["Green", "Light shades"],
    luckyStone: "Emerald",
    favroableStone: ["Green Jade", "Peridot", "Yellow Sapphire"]
  },

  {
    id: "dob24",
    day: 24,
    symbol: "24",
    name: "Date of Birth 24",
    rulingPlanet: "Venus",
    shortDesc: "Stable Venus expression with care and harmony.",
    fullDesc: "You usually value family, comfort, and emotional stability deeply. Responsibility often becomes a natural part of life. Supportive relationships strengthen your confidence. Emotional burden may rise when duties increase. Balanced affection usually creates peace.",
    positiveTraits: ["Responsibility", "Harmony", "Care"],
    cautionTraits: ["Emotional burden", "Attachment"],
    career: ["Hospitality", "Finance", "Support roles"],
    health: ["Kidney", "Hormonal sensitivity"],
    luckyNumbers: [6, 2, 4],
    luckyDays: ["Friday", "Monday"],
    luckyColors: ["White", "Pink"],
    luckyStone: "Diamond",
    favroableStone: ["White Zircon", "Opal", "Pearl"]
  },

  {
    id: "dob25",
    day: 25,
    symbol: "25",
    name: "Date of Birth 25",
    rulingPlanet: "Ketu",
    shortDesc: "Analytical mind and hidden intuition become strong.",
    fullDesc: "You usually study people and situations deeply before trusting. Quiet observation often becomes your hidden strength. Intuition may guide important choices. Worry can increase when thoughts remain unresolved. Inner clarity usually improves decision-making.",
    positiveTraits: ["Analysis", "Intuition", "Observation"],
    cautionTraits: ["Worry", "Isolation"],
    career: ["Research", "Writing", "Healing"],
    health: ["Stress", "Sleep issues"],
    luckyNumbers: [7, 2],
    luckyDays: ["Monday", "Friday"],
    luckyColors: ["Light Green", "White"],
    luckyStone: "Cat's Eye",
    favroableStone: ["Alexandrite", "Moonstone", "Emerald"]
  },

  {
    id: "dob26",
    day: 26,
    symbol: "26",
    name: "Date of Birth 26",
    rulingPlanet: "Saturn",
    shortDesc: "Responsibility and delayed rewards shape this date.",
    fullDesc: "You usually become practical through responsibility and experience. Security and stability often remain strong concerns. Slow progress may still create lasting strength. Emotional heaviness may appear under pressure. Discipline usually improves long-term achievement.",
    positiveTraits: ["Responsibility", "Endurance", "Practical maturity"],
    cautionTraits: ["Delay frustration", "Heaviness"],
    career: ["Finance", "Industry", "Administration"],
    health: ["Joints", "Digestive heaviness"],
    luckyNumbers: [8, 6],
    luckyDays: ["Saturday", "Friday"],
    luckyColors: ["Blue", "Grey"],
    luckyStone: "Blue Sapphire",
    favroableStone: ["Amethyst", "Iolite", "Diamond"]
  },

  {
    id: "dob27",
    day: 27,
    symbol: "27",
    name: "Date of Birth 27",
    rulingPlanet: "Mars",
    shortDesc: "Courage joins intuition for purposeful action.",
    fullDesc: "You usually combine courage with thoughtful judgement. Protective instincts often remain strong in important situations. Inner wisdom may guide decisions better with maturity. Emotional intensity can create pressure internally. Balanced action usually brings meaningful results.",
    positiveTraits: ["Courage", "Wisdom", "Duty"],
    cautionTraits: ["Inner conflict", "Sharp reaction"],
    career: ["Medical", "Leadership", "Defence"],
    health: ["Blood heat", "Inflammation"],
    luckyNumbers: [9, 2, 7],
    luckyDays: ["Tuesday", "Monday"],
    luckyColors: ["Red", "White"],
    luckyStone: "Red Coral",
    favroableStone: ["Carnelian", "Bloodstone", "Cat's Eye"]
  },

  {
    id: "dob28",
    day: 28,
    symbol: "28",
    name: "Date of Birth 28",
    rulingPlanet: "Sun",
    shortDesc: "Leadership develops through struggle and self-correction.",
    fullDesc: "You usually seek independence and visible recognition. Life may teach confidence through repeated practical lessons. Leadership grows stronger after setbacks. Relationship clashes may appear when ego becomes active. Mature effort usually brings stable authority.",
    positiveTraits: ["Leadership", "Resilience", "Confidence"],
    cautionTraits: ["Ego clashes", "Disappointment"],
    career: ["Administration", "Business", "Planning"],
    health: ["Head stress", "Blood pressure"],
    luckyNumbers: [1, 10, 19, 28],
    luckyDays: ["Sunday", "Thursday"],
    luckyColors: ["Orange", "Golden"],
    luckyStone: "Ruby",
    favroableStone: ["Red Garnet", "Sunela", "Hessonite"]
  },

  {
    id: "dob29",
    day: 29,
    symbol: "29",
    name: "Date of Birth 29",
    rulingPlanet: "Moon",
    shortDesc: "Highly sensitive vibration with strong intuition.",
    fullDesc: "You usually feel emotional situations deeply and quickly. Intuition may become one of your strongest natural gifts. Relationships strongly affect inner peace. Mood shifts may create uncertainty in decisions. Emotional clarity usually improves progress.",
    positiveTraits: ["Intuition", "Empathy", "Sensitivity"],
    cautionTraits: ["Mood shifts", "Emotional hurt"],
    career: ["Creative work", "Healing", "Counselling"],
    health: ["Cold", "Mental stress"],
    luckyNumbers: [2, 11, 29],
    luckyDays: ["Monday", "Sunday"],
    luckyColors: ["White", "Cream"],
    luckyStone: "Pearl",
    favroableStone: ["Moonstone", "Opal", "Red Coral"]
  },

  {
    id: "dob30",
    day: 30,
    symbol: "30",
    name: "Date of Birth 30",
    rulingPlanet: "Jupiter",
    shortDesc: "Jupiter expands ideas and expression strongly.",
    fullDesc: "You usually think broadly and express ideas with confidence. Communication often becomes an important strength in life. Social respect may matter deeply. Scattered effort can delay results. Focused learning usually improves success.",
    positiveTraits: ["Expression", "Wisdom", "Optimism"],
    cautionTraits: ["Overexpectation", "Scattered focus"],
    career: ["Teaching", "Writing", "Advisory"],
    health: ["Throat", "Liver tendency"],
    luckyNumbers: [3, 12, 21, 30],
    luckyDays: ["Thursday", "Sunday"],
    luckyColors: ["Yellow", "Cream"],
    luckyStone: "Yellow Sapphire",
    favroableStone: ["Citrine", "Yellow Topaz", "Ruby"]
  },

  {
    id: "dob31",
    day: 31,
    symbol: "31",
    name: "Date of Birth 31",
    rulingPlanet: "Rahu",
    shortDesc: "Independent thinking with controlled originality.",
    fullDesc: "You usually think differently but reveal ideas carefully. Practical control often becomes stronger than quick expression. Stable growth suits you better than sudden movement. Mental isolation may appear during stress. Patience usually converts originality into achievement.",
    positiveTraits: ["Originality", "Control", "Practical depth"],
    cautionTraits: ["Isolation", "Resistance"],
    career: ["Technology", "Planning", "Research"],
    health: ["Stress", "Digestive irregularity"],
    luckyNumbers: [4, 1],
    luckyDays: ["Sunday", "Saturday"],
    luckyColors: ["Grey", "Blue"],
    luckyStone: "Hessonite",
    favroableStone: ["Honey Garnet", "Cinnamon Stone", "Ruby"]
  }
];

export function getDOBPrediction(dd) {
  const day = parseInt(dd, 10);
  if (isNaN(day) || day < 1 || day > 31) return null;
  return DOB_NUMBERS.find((d) => d.day === day) ?? null;
}

