export const FAVORABLE_STONES = {
  1: ["Ruby", "Red Garnet", "Sunela"],
  2: ["Pearl", "Moonstone", "Opal", "White Coral"],
  3: ["Yellow Sapphire", "Citrine", "Yellow Topaz"],
  4: ["Hessonite", "Honey Garnet", "Cinnamon Stone"],
  5: ["Emerald", "Green Jade", "Peridot"],
  6: ["Diamond", "White Zircon", "Opal"],
  7: ["Cat's Eye", "Alexandrite", "Moonstone"],
  8: ["Blue Sapphire", "Amethyst", "Iolite"],
  9: ["Red Coral", "Carnelian", "Bloodstone"],

  10: ["Ruby", "Red Garnet", "Sunela"],
  11: ["Pearl", "Moonstone", "Opal", "Ruby"],
  12: ["Yellow Sapphire", "Citrine", "Yellow Topaz", "Pearl"],
  13: ["Hessonite", "Honey Garnet", "Cinnamon Stone", "Yellow Sapphire"],
  14: ["Emerald", "Green Jade", "Peridot", "Diamond"],
  15: ["Diamond", "White Zircon", "Opal", "Emerald"],
  16: ["Cat's Eye", "Alexandrite", "Moonstone", "Pearl"],
  17: ["Blue Sapphire", "Amethyst", "Iolite", "Ruby"],
  18: ["Red Coral", "Carnelian", "Bloodstone", "Pearl"],
  19: ["Ruby", "Red Garnet", "Sunela"],
  20: ["Pearl", "Moonstone", "Opal", "White Coral"],

  21: ["Yellow Sapphire", "Citrine", "Yellow Topaz", "Pearl"],
  22: ["Hessonite", "Honey Garnet", "Cinnamon Stone", "Blue Sapphire"],
  23: ["Emerald", "Green Jade", "Peridot", "Yellow Sapphire"],
  24: ["Diamond", "White Zircon", "Opal", "Pearl"],
  25: ["Cat's Eye", "Alexandrite", "Moonstone", "Emerald"],
  26: ["Blue Sapphire", "Amethyst", "Iolite", "Diamond"],
  27: ["Red Coral", "Carnelian", "Bloodstone", "Cat's Eye"],
  28: ["Ruby", "Red Garnet", "Sunela", "Hessonite"],
  29: ["Pearl", "Moonstone", "Opal", "Red Coral"],
  30: ["Yellow Sapphire", "Citrine", "Yellow Topaz", "Ruby"],
  31: ["Hessonite", "Honey Garnet", "Cinnamon Stone", "Ruby"],
};
