// ============================================================
// sunSignEn.js — English Sun Sign Master Source
// rootNumberEn.js style architecture
// ============================================================

export const SUN_SIGNS = [
  {
    id: "mesh",
    symbol: "♈",
    zodiacNumber: 1,
    name: "Aries",
    rulingPlanet: "Mars",
    rulingNumber: 9,
    dateRange: "Apr 14 – May 14",
    startMonth: 4,
    startDay: 14,
    endMonth: 5,
    endDay: 14,
    shortDesc: "Bold, active, and naturally independent by nature.",
    fullDesc: "Aries Sun sign usually gives courage, direct action, and self-driven energy. Such people often prefer making their own decisions and moving ahead without waiting for others. Leadership instinct appears naturally in important situations. Quick reactions are common, especially when challenged. With proper focus, Aries builds strong personal identity and visible success.",
    positiveTraits: ["Leadership", "Courage", "Independence"],
    cautionTraits: ["Anger", "Impatience", "Overreaction"],
    career: ["Administration", "Police", "Engineering"],
    health: ["Head pain", "Blood heat", "Fever tendency"],
    luckyNumbers: [1, 9, 3],
    luckyDays: ["Tuesday", "Sunday"],
    luckyColors: ["Red"],
    luckyStone: "Red Coral",
    otherFavorableStones: ["Garnet", "Red Agate"],
  },
  {
    id: "vrishabh",
    symbol: "♉",
    zodiacNumber: 2,
    name: "Taurus",
    rulingPlanet: "Venus",
    rulingNumber: 6,
    dateRange: "May 15 – Jun 14",
    startMonth: 5,
    startDay: 15,
    endMonth: 6,
    endDay: 14,
    shortDesc: "Steady, patient, and grounded in practical life.",
    fullDesc: "Taurus Sun sign usually creates calm determination, material stability, and steady progress through patience. Such people prefer security and practical results in life. Their decisions are often slow but reliable. Once committed, they rarely step back easily. Stability becomes their strongest strength over time.",
    positiveTraits: ["Patience", "Practicality", "Persistence"],
    cautionTraits: ["Stubbornness", "Possessiveness", "Slow reaction"],
    career: ["Finance", "Hospitality", "Cosmetics"],
    health: ["Throat issues", "Cold tendency", "Digestive heaviness"],
    luckyNumbers: [6, 2, 5],
    luckyDays: ["Friday", "Monday"],
    luckyColors: ["White", "Cream"],
    luckyStone: "Diamond",
    otherFavorableStones: ["Opal", "Zircon"],
  },
  {
    id: "mithun",
    symbol: "♊",
    zodiacNumber: 3,
    name: "Gemini",
    rulingPlanet: "Mercury",
    rulingNumber: 5,
    dateRange: "Jun 15 – Jul 15",
    startMonth: 6,
    startDay: 15,
    endMonth: 7,
    endDay: 15,
    shortDesc: "Quick mind and strong communication ability.",
    fullDesc: "Gemini Sun sign usually gives fast thinking, adaptability, and strong expression through words and ideas. Such people learn quickly and respond well in changing situations. Communication becomes a major strength in daily life. Their mind often explores multiple directions together. With focus, Gemini achieves excellent intellectual growth.",
    positiveTraits: ["Intelligence", "Adaptability", "Communication"],
    cautionTraits: ["Restlessness", "Dual thinking", "Instability"],
    career: ["Writing", "Teaching", "Media"],
    health: ["Nerves", "Respiratory issues", "Sleep disturbance"],
    luckyNumbers: [5, 6, 1],
    luckyDays: ["Wednesday"],
    luckyColors: ["Green"],
    luckyStone: "Emerald",
    otherFavorableStones: ["Green Onyx", "Peridot"],
  },

  {
    id: "kark",
    symbol: "♋",
    zodiacNumber: 4,
    name: "Cancer",
    rulingPlanet: "Moon",
    rulingNumber: 2,
    dateRange: "Jul 16 – Aug 16",
    startMonth: 7,
    startDay: 16,
    endMonth: 8,
    endDay: 16,
    shortDesc: "Emotionally deep, protective, and intuitive.",
    fullDesc: "Cancer Sun sign usually creates emotional depth, family attachment, and strong inner sensitivity. Such people often value emotional security deeply. Their intuition works strongly in relationships and daily choices. Mood changes may appear under pressure. Inner balance helps them grow with maturity.",
    positiveTraits: ["Sensitivity", "Care", "Intuition"],
    cautionTraits: ["Mood swings", "Overthinking", "Emotional pressure"],
    career: ["Travel", "Food", "Public dealing"],
    health: ["Cold", "Chest sensitivity", "Digestion"],
    luckyNumbers: [2, 7, 1],
    luckyDays: ["Monday"],
    luckyColors: ["White"],
    luckyStone: "Pearl",
    otherFavorableStones: ["Moonstone"],
  },
  {
    id: "simha",
    symbol: "♌",
    zodiacNumber: 5,
    name: "Leo",
    rulingPlanet: "Sun",
    rulingNumber: 1,
    dateRange: "Aug 17 – Sep 16",
    startMonth: 8,
    startDay: 17,
    endMonth: 9,
    endDay: 16,
    shortDesc: "Strong presence, confidence, and natural authority.",
    fullDesc: "Leo Sun sign usually gives visible confidence, leadership instinct, and desire for recognition. Such people naturally wish to stand with dignity. Their presence often attracts attention in social settings. They perform best when trusted with responsibility. Balanced confidence brings long-term respect.",
    positiveTraits: ["Confidence", "Authority", "Generosity"],
    cautionTraits: ["Ego", "Rigidity", "Respect sensitivity"],
    career: ["Government", "Leadership", "Administration"],
    health: ["Heart care", "Heat imbalance", "Digestion"],
    luckyNumbers: [1, 4, 9],
    luckyDays: ["Sunday"],
    luckyColors: ["Golden", "Orange"],
    luckyStone: "Ruby",
    otherFavorableStones: ["Sunstone"],
  },
  {
    id: "kanya",
    symbol: "♍",
    zodiacNumber: 6,
    name: "Virgo",
    rulingPlanet: "Mercury",
    rulingNumber: 5,
    dateRange: "Sep 17 – Oct 16",
    startMonth: 9,
    startDay: 17,
    endMonth: 10,
    endDay: 16,
    shortDesc: "Detail-focused, analytical, and disciplined.",
    fullDesc: "Virgo Sun sign usually supports precision, structured thinking, and practical judgement. Such people notice details that others often miss. Their working style remains disciplined and methodical. Sometimes they think too deeply before acting. Proper confidence improves their efficiency greatly.",
    positiveTraits: ["Detail focus", "Logic", "Discipline"],
    cautionTraits: ["Overthinking", "Self-criticism", "Worry tendency"],
    career: ["Accounting", "Writing", "Research"],
    health: ["Digestive issues", "Nervous strain", "Stress"],
    luckyNumbers: [5, 3, 6],
    luckyDays: ["Wednesday"],
    luckyColors: ["Green", "Light Brown"],
    luckyStone: "Emerald",
    otherFavorableStones: ["Green Jade"],
  },
  {
    id: "tula",
    symbol: "♎",
    zodiacNumber: 7,
    name: "Libra",
    rulingPlanet: "Venus",
    rulingNumber: 6,
    dateRange: "Oct 17 – Nov 15",
    startMonth: 10,
    startDay: 17,
    endMonth: 11,
    endDay: 15,
    shortDesc: "Balanced thinking and social grace.",
    fullDesc: "Libra Sun sign usually gives diplomacy, harmony, and relationship awareness. Such people usually observe both sides before deciding. Social grace becomes a natural advantage for them. They value fairness and peaceful surroundings. Clear decisions strengthen their success.",
    positiveTraits: ["Diplomacy", "Grace", "Social sense"],
    cautionTraits: ["Indecision", "Dependency", "Too much balancing"],
    career: ["Business", "Law", "Finance"],
    health: ["Back pain", "Kidney care", "Sugar balance"],
    luckyNumbers: [6, 2, 9],
    luckyDays: ["Friday"],
    luckyColors: ["White", "Pink"],
    luckyStone: "Diamond",
    otherFavorableStones: ["Opal"],
  },
  {
    id: "vrishchik",
    symbol: "♏",
    zodiacNumber: 8,
    name: "Scorpio",
    rulingPlanet: "Mars",
    rulingNumber: 9,
    dateRange: "Nov 16 – Dec 15",
    startMonth: 11,
    startDay: 16,
    endMonth: 12,
    endDay: 15,
    shortDesc: "Deep, intense, and mentally powerful.",
    fullDesc: "Scorpio Sun sign usually creates inner strength, secrecy, and strong emotional depth. Such people often keep feelings guarded inside. Their willpower becomes strong in difficult phases. Emotional reactions can remain intense internally. Correct direction turns this depth into power.",
    positiveTraits: ["Determination", "Depth", "Fearlessness"],
    cautionTraits: ["Revenge tendency", "Mental aggression", "Emotional hardness"],
    career: ["Medicine", "Research", "Engineering"],
    health: ["Hormonal issues", "Skin heat", "Digestive stress"],
    luckyNumbers: [9, 1, 2],
    luckyDays: ["Tuesday"],
    luckyColors: ["Red", "Maroon"],
    luckyStone: "Red Coral",
    otherFavorableStones: ["Red Garnet"],
  },
  {
    id: "dhanu",
    symbol: "♐",
    zodiacNumber: 9,
    name: "Sagittarius",
    rulingPlanet: "Jupiter",
    rulingNumber: 3,
    dateRange: "Dec 16 – Jan 13",
    startMonth: 12,
    startDay: 16,
    endMonth: 1,
    endDay: 13,
    shortDesc: "Wisdom, expansion, and broad vision.",
    fullDesc: "Sagittarius Sun sign usually gives optimism, knowledge-seeking nature, and growth-oriented thinking. Such people often look for meaning beyond routine life. Learning and guidance attract them naturally. They prefer freedom in decisions and ideas. Discipline makes their growth more stable.",
    positiveTraits: ["Wisdom", "Optimism", "Morality"],
    cautionTraits: ["Temper", "Overconfidence", "Hasty decisions"],
    career: ["Teaching", "Law", "Advisory"],
    health: ["Liver care", "Gas tendency", "Thigh weakness"],
    luckyNumbers: [3, 1, 9],
    luckyDays: ["Thursday"],
    luckyColors: ["Yellow"],
    luckyStone: "Yellow Sapphire",
    otherFavorableStones: ["Citrine"],
  },
  {
    id: "makar",
    symbol: "♑",
    zodiacNumber: 10,
    name: "Capricorn",
    rulingPlanet: "Saturn",
    rulingNumber: 8,
    dateRange: "Jan 14 – Feb 11",
    startMonth: 1,
    startDay: 14,
    endMonth: 2,
    endDay: 11,
    shortDesc: "Patience, discipline, and responsibility.",
    fullDesc: "Capricorn Sun sign usually builds life through steady effort, maturity, and structured progress. Such people believe in results earned through patience. Responsibility often appears early in life. Their growth may look slow but becomes stable. Persistence gives them lasting success.",
    positiveTraits: ["Discipline", "Persistence", "Practicality"],
    cautionTraits: ["Rigidity", "Emotional dryness", "Slow expression"],
    career: ["Construction", "Administration", "Industry"],
    health: ["Bones", "Joint pain", "Gas issues"],
    luckyNumbers: [8, 4, 6],
    luckyDays: ["Saturday"],
    luckyColors: ["Blue", "Grey"],
    luckyStone: "Blue Sapphire",
    otherFavorableStones: ["Amethyst"],
  },
  {
    id: "kumbh",
    symbol: "♒",
    zodiacNumber: 11,
    name: "Aquarius",
    rulingPlanet: "Saturn",
    rulingNumber: 8,
    dateRange: "Feb 12 – Mar 12",
    startMonth: 2,
    startDay: 12,
    endMonth: 3,
    endDay: 12,
    shortDesc: "Independent thought and original vision.",
    fullDesc: "Aquarius Sun sign usually supports originality, reform, and detached thinking. Such people often think differently from common patterns. New ideas attract them strongly. Emotional distance may appear in close matters. Clear direction helps their originality become productive.",
    positiveTraits: ["Innovation", "Independence", "Depth"],
    cautionTraits: ["Detachment", "Unpredictability", "Sudden shifts"],
    career: ["Technology", "Research", "Advisory"],
    health: ["Blood circulation", "Nerves", "Fatigue"],
    luckyNumbers: [8, 4, 5],
    luckyDays: ["Saturday"],
    luckyColors: ["Blue"],
    luckyStone: "Blue Sapphire",
    otherFavorableStones: ["Blue Topaz"],
  },
  {
    id: "meen",
    symbol: "♓",
    zodiacNumber: 12,
    name: "Pisces",
    rulingPlanet: "Jupiter",
    rulingNumber: 3,
    dateRange: "Mar 13 – Apr 13",
    startMonth: 3,
    startDay: 13,
    endMonth: 4,
    endDay: 13,
    shortDesc: "Compassionate, intuitive, and inwardly deep.",
    fullDesc: "Pisces Sun sign usually gives emotional understanding, imagination, and spiritual softness. Such people often sense others deeply without words. Creative thinking develops naturally in them. Emotional flow can affect practical decisions. Balance helps their inner gifts shine fully."
    positiveTraits: ["Compassion", "Imagination", "Spirituality"],
    cautionTraits: ["Emotional escape", "Indecision", "Practical weakness"],
    career: ["Healing", "Teaching", "Creative arts"],
    health: ["Cold tendency", "Sleep imbalance", "Feet sensitivity"],
    luckyNumbers: [3, 7, 2],
    luckyDays: ["Thursday", "Monday"],
    luckyColors: ["Yellow", "Cream"],
    luckyStone: "Yellow Sapphire",
    otherFavorableStones: ["Citrine", "Yellow Topaz"],
  }
];

export function getSunSign(dd, mm) {
  const day = parseInt(dd, 10);
  const month = parseInt(mm, 10);

  for (const sign of SUN_SIGNS) {
    const { startMonth, startDay, endMonth, endDay } = sign;

    if (startMonth > endMonth) {
      if (
        (month === startMonth && day >= startDay) ||
        (month === endMonth && day <= endDay) ||
        month > startMonth ||
        month < endMonth
      ) {
        return sign;
      }
    } else {
      if (
        (month === startMonth && day >= startDay) ||
        (month > startMonth && month < endMonth) ||
        (month === endMonth && day <= endDay)
      ) {
        return sign;
      }
    }
  }

  return null;
}
